### ISSUE TITLE
Fix Deploy for Zero Downtime Strategy

### ISSUE THREAD

**Issue by codelitt** [codelittinc/incubator-resources#32]
There's a slight downtime in what we currently have published. It's not major, but still if we build the new containers, update nginx, and then destroy old container we should be near to a proper blue-green deploy eh @halissonvit @kaiomagalhaes

**Comment by kaiomagalhaes** [comment]
@codelitt I was talking with halisson about it and we came to the conclusion that to have a proper blue-green deploy we will need more than that, we need for example to deal with the current sessions because when we destroy the container we are destroying the user sessions so we need work on it too.

But yeah what you said will get us near to blue-green deploy

**Comment by codelitt** [comment]
@kaiomagalhaes Yes. That is true. Well we could get very near to the blue-green strategy. I guess create another issue to go FULL on into it although I imagine that is a bit more involved.

**Comment by kaiomagalhaes** [comment]
Nowadays there are better ways to manage blue-green deployments without manual work.
